quarto-required: ">= 1.4"

project:
  output-dir: docs
  execute-dir: project
  render:
    - "**/*.qmd"
    - "!slides/slides_template/*.qmd"





execute:
  echo: false
  warning: false
  message: false

format:
  revealjs:
    slide-number: c/t
    show-slide-number: all
    embed-resources: false
    preview-links: false
    theme: [default, slides/slides_template/assets/sdaia.scss]
    logo: slides/slides_template/assets/sdaia.svg
    transition: slide
    transition-speed: default
    background-transition: fade
    title-slide-attributes:
      data-background-image: "slides/slides_template/assets/anim.svg"
      data-background-opacity: "0.15"
      data-background-size: "cover"
    chalkboard: 
      buttons: true
    date: ""
    multiplex: false
    help: true
    progress: true
    history: true
    hide-inactive-cursor: true
    strip-comments: true
    center: false
    incremental: false
    code-copy: true
    code-line-numbers: true
    scrollable: false
    pdf-separate-fragments: false
    filters:
      - slides/slides_template/assets/splash.lua
    plugins: [menu]
    menu:
      custom:
        - title: "Index"
          icon: "<svg width='1.8rem' viewBox='0 0 24 24'><path d='M5 7h14M5 12h14M5 17h7' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'/></svg>"
          src: "../../index.html"
    include-in-header:
      - file: slides/slides_template/assets/favicon.html
          
